fix v \s\s 1 2 3
aurelien-rainone/gobj pull request #2
Opened 2022-03-16 08:18 UTC by 514366607

Error By 3ds Max Wavefront OBJ Exporter

2022-03-18 08:27 UTC, arl requested changes
Thank you for that.
Can we move the regex compilation our of the Decode path? Then I'll merge it.

2022-03-18 08:27 UTC, arl commented on decoder.go
> +		re, _ := regexp.Compile(`\s+`)
Would have preferred another way to check that an user expression. 
In any case, the regex compilation should be done outside of the loop, and preferably once for all, with a `regex.MustCompile` global block

2022-04-11 04:18 UTC, 514366607 commented
Submitted, please review.

2022-04-11 05:31 UTC, arl approved these changes
LGTM

Thank you🎉

2022-04-11 05:31 UTC, merged